// Seed data for Auro Heal Dashboard
window.AURO_DATA = {
  environments: [
    {
      id: "aws",
      name: "AWS",
      kind: "Public cloud",
      region: "us-east-1, eu-west-2",
      instances: 42,
      errors: 7,
      health: 78,
      status: "degraded",
    },
    {
      id: "azure",
      name: "Azure",
      kind: "Public cloud",
      region: "eastus, westeurope",
      instances: 31,
      errors: 3,
      health: 91,
      status: "healthy",
    },
    {
      id: "gcp",
      name: "GCP",
      kind: "Public cloud",
      region: "us-central1",
      instances: 18,
      errors: 5,
      health: 84,
      status: "degraded",
    },
    {
      id: "vps",
      name: "VPS",
      kind: "Self-hosted",
      region: "Hetzner · DO · Linode",
      instances: 12,
      errors: 2,
      health: 95,
      status: "healthy",
    },
  ],

  apps: [
    {
      id: "app-01",
      name: "checkout-service",
      env: "aws",
      lang: "Node.js 20",
      severity: "critical",
      occurrences: 142,
      lastSeen: "2 min ago",
      errorType: "UnhandledPromiseRejection",
      error:
        "TypeError: Cannot read properties of undefined (reading 'token')\n    at validatePayment (/srv/checkout/payments.js:84:31)\n    at processOrder (/srv/checkout/orders.js:212:14)\n    at async POST /api/v1/checkout",
      logExcerpt: [
        "[2026-05-17 09:14:22] WARN  payment.gateway retry exhausted (3/3)",
        "[2026-05-17 09:14:22] ERROR uncaughtException in worker pid=3814",
        "[2026-05-17 09:14:22] ERROR TypeError: Cannot read properties of undefined (reading 'token')",
      ],
      repo: "github.com/auro/checkout-service",
      branch: "main",
    },
    {
      id: "app-02",
      name: "auth-gateway",
      env: "aws",
      lang: "Go 1.22",
      severity: "high",
      occurrences: 38,
      lastSeen: "11 min ago",
      errorType: "PanicRecovered",
      error:
        "panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV] at jwt.Verify (claims.go:117)",
      logExcerpt: [
        "[2026-05-17 09:03:01] INFO  request received POST /v2/token",
        "[2026-05-17 09:03:01] ERROR jwt verification panic: nil claims block",
        "[2026-05-17 09:03:01] WARN  recovered, returning 500",
      ],
      repo: "github.com/auro/auth-gateway",
      branch: "main",
    },
    {
      id: "app-03",
      name: "warehouse-sync",
      env: "azure",
      lang: "Python 3.12",
      severity: "high",
      occurrences: 24,
      lastSeen: "26 min ago",
      errorType: "DataIntegrityError",
      error:
        "psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"sku_idx\"\n  detail: Key (sku)=(SKU-44291) already exists.",
      logExcerpt: [
        "[2026-05-17 08:48:11] INFO  sync batch 488 started · 1240 rows",
        "[2026-05-17 08:48:14] ERROR UniqueViolation on sku_idx · row 812",
        "[2026-05-17 08:48:14] ERROR batch rolled back",
      ],
      repo: "github.com/auro/warehouse-sync",
      branch: "release/2.4",
    },
    {
      id: "app-04",
      name: "notifications-fanout",
      env: "gcp",
      lang: "Rust 1.78",
      severity: "medium",
      occurrences: 15,
      lastSeen: "44 min ago",
      errorType: "ChannelClosed",
      error:
        "Error: send on closed channel\n  in tokio::task fanout::dispatch::worker (workers.rs:201)",
      logExcerpt: [
        "[2026-05-17 08:30:55] WARN  pubsub backpressure detected",
        "[2026-05-17 08:31:02] ERROR send on closed channel",
        "[2026-05-17 08:31:02] WARN  worker restart 4/10",
      ],
      repo: "github.com/auro/notifications-fanout",
      branch: "main",
    },
    {
      id: "app-05",
      name: "reporting-pipeline",
      env: "gcp",
      lang: "Python 3.11",
      severity: "medium",
      occurrences: 9,
      lastSeen: "1 h ago",
      errorType: "TimeoutError",
      error:
        "TimeoutError: BigQuery job exceeded 300s wall clock\n  query: rollup_daily_revenue_v3",
      logExcerpt: [
        "[2026-05-17 08:02:00] INFO  scheduling rollup_daily_revenue_v3",
        "[2026-05-17 08:07:00] ERROR job timed out after 300s",
      ],
      repo: "github.com/auro/reporting-pipeline",
      branch: "main",
    },
    {
      id: "app-06",
      name: "edge-router",
      env: "vps",
      lang: "Node.js 20",
      severity: "low",
      occurrences: 4,
      lastSeen: "2 h ago",
      errorType: "DeprecationWarning",
      error:
        "DeprecationWarning: Buffer() is deprecated due to security and usability issues.\n  at parseInbound (router/parse.js:48:9)",
      logExcerpt: [
        "[2026-05-17 07:11:42] WARN  Buffer() deprecation at router/parse.js:48",
      ],
      repo: "github.com/auro/edge-router",
      branch: "main",
    },
  ],

  fixed: [
    {
      id: "fix-01",
      app: "billing-cron",
      env: "aws",
      errorType: "MemoryLeak",
      summary: "Patched dangling event listener in invoice generator",
      filesChanged: 3,
      additions: 41,
      deletions: 18,
      commit: "a4f8c91",
      branch: "main",
      repo: "github.com/auro/billing-cron",
      fixedAt: "Today · 07:42",
      duration: "1m 38s",
    },
    {
      id: "fix-02",
      app: "image-thumbnailer",
      env: "gcp",
      errorType: "OOMKilled",
      summary: "Stream-decoded large uploads instead of buffering in memory",
      filesChanged: 2,
      additions: 28,
      deletions: 12,
      commit: "1c0b22d",
      branch: "main",
      repo: "github.com/auro/image-thumbnailer",
      fixedAt: "Yesterday · 22:14",
      duration: "2m 04s",
    },
    {
      id: "fix-03",
      app: "search-indexer",
      env: "azure",
      errorType: "ConnectionRefused",
      summary: "Added exponential backoff + circuit breaker to ES client",
      filesChanged: 4,
      additions: 92,
      deletions: 7,
      commit: "9ee3417",
      branch: "release/2.4",
      repo: "github.com/auro/search-indexer",
      fixedAt: "Yesterday · 16:51",
      duration: "3m 12s",
    },
    {
      id: "fix-04",
      app: "user-profile-api",
      env: "vps",
      errorType: "RaceCondition",
      summary: "Wrapped avatar write in transactional advisory lock",
      filesChanged: 1,
      additions: 14,
      deletions: 3,
      commit: "77b2e08",
      branch: "main",
      repo: "github.com/auro/user-profile-api",
      fixedAt: "May 16 · 14:09",
      duration: "1m 12s",
    },
    {
      id: "fix-05",
      app: "metrics-collector",
      env: "aws",
      errorType: "NullPointer",
      summary: "Guarded missing tag map before dimension expansion",
      filesChanged: 2,
      additions: 19,
      deletions: 4,
      commit: "44a91be",
      branch: "main",
      repo: "github.com/auro/metrics-collector",
      fixedAt: "May 15 · 11:30",
      duration: "0m 51s",
    },
  ],

  // Steps shown during the live "fixing" stage. Mix of phases so it feels like
  // a real pipeline rather than a single LLM call.
  fixSteps: [
    { phase: "clone",   label: "Cloning repository",       detail: "git clone --depth=20 {repo} -b {branch}" },
    { phase: "ingest",  label: "Ingesting recent logs",    detail: "Pulled 4,812 lines · last 30 min window" },
    { phase: "analyze", label: "Locating root cause",      detail: "Stack trace mapped to payments.js:84" },
    { phase: "context", label: "Reading surrounding code", detail: "8 files · 612 LOC loaded into context" },
    { phase: "reason",  label: "Reasoning about fix",      detail: "Considering 3 candidate patches" },
    { phase: "patch",   label: "Generating patch",         detail: "+41 / −18 across 3 files" },
    { phase: "test",    label: "Running test suite",       detail: "184 tests passed · 0 failed · 2.4s" },
    { phase: "lint",    label: "Static analysis",          detail: "eslint · typecheck · semgrep — clean" },
    { phase: "verify",  label: "Replaying failing trace",  detail: "Original error no longer reproduces" },
  ],
};
